### ISSUE TITLE
ui - Date analysis and formatting

### ISSUE THREAD

**Issue by admirkrilasevic** [digiexpress-io/digiexpress-parent#110]
- What date formats are there?
- What date formats do we need?
- Where does date format matter?
- Do time zones matter and where?

#### Task 1 : Date analysis
Extract all the variants of the date formats
Make a list of proposals of when and why we should be using what formats, and what kind of accuracy (time, no time, zoned, etc.) 

#### Task 2: Date formatting
Based on an agreed plan after analysis, format dates across the site

**Comment by admirkrilasevic** [comment]
Task 2:

- [ ] Change LocalDateTime to Instant on backend

**Comment by jocelynmutso** [comment]
Task 3:

- [ ] Create Timestamp formatter component
