### ISSUE TITLE
SysConfig Frontend

### ISSUE THREAD

**Issue by olev-mutso** [digiexpress-io/digiexpress-parent#196]
### Problem description
Release management is fragmented between 4 different application:
1. Wrench (data processing)
2. Stencil (expose services)
3. Dialob (data collection)
4. Tasks (tasks management contains linking between previous 3)

This kind of fragmentation brings in unnecessary complexity it would make things a lot easier to have single release functionality that takes care of all the linked application on it's own.

### Solution requirements
Create single source of truth from where all releases and configurations can be managed.

Service names must come from Stencil because it already contains (named)entry points for data collection. 
These entry points serve 2 purposes: 
1. Entry point provides: technical name and localized names
2. Each entry point is linked to [1 to *] articles(localized markdown content), this is optional
Each service must be linked to Dialob form(data collection) and Wrench flow(data processing)

Create 1 view where all of the applications can be linked together:
1. stencil release/branch can be selected (service names must come from stencil)
  - for releases, services can not be changed, they can be only enabled/disabled
  - for branches, services can be enabled/disabled and edited/deleted
2. wrench release/branch can be selected (flow names)
  - for releases, flows can not be changed, they can be only selected
  - for branches, flows can be created/updated
3. dialob release/latest can be selected
  - for releases, form can not be changed, they can only be selected
  - for branches, forms can be created/updated
4. create release, this must create one release of all the assets and also behind the scenes create delegate releases for each application.

![release drawio](https://github.com/digiexpress-io/digiexpress-parent/assets/4125731/21b3d54c-1d4f-4038-9994-b30698bdbf34)

![SysConfig-Process drawio](https://github.com/digiexpress-io/digiexpress-parent/assets/4125731/1ccf1ee0-9b88-4782-986f-c19929b66c5d)

**Comment by Tatuk** [comment]
closed as not needed
